name: launch_at_startup
description: This plugin allows Flutter desktop apps to Auto launch on startup / login.
version: 0.2.2
homepage: https://github.com/leanflutter/launch_at_startup

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
  win32_registry: ^1.0.2

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
